import Topbar from "../components/Topbar";
import { useSidebar } from "../context/SidebarContext";
import { recentReports, reportTypes } from "../data/reports";

export default function Reports() {
  const { openSidebar } = useSidebar();

  return (
    <>
      <Topbar title="Reports" subtitle="Generate and download system reports." onMenuClick={openSidebar} />

      <div className="p-3 p-lg-4">
        <div className="row g-3 mb-4">
          {reportTypes.map((r) => (
            <div className="col-6 col-lg-3" key={r.key}>
              <div className="card-surface p-3 h-100 d-flex flex-column">
                <span className="icon-circle bg-primary-brand text-white mb-2" style={{ width: 40, height: 40 }}>
                  <i className={`bi ${r.icon}`} />
                </span>
                <p className="fw-semibold mb-1" style={{ fontSize: "0.92rem" }}>{r.title}</p>
                <p className="text-muted-brand mb-3" style={{ fontSize: "0.78rem" }}>{r.subtitle}</p>
                <button className="btn btn-brand rounded-3 mt-auto btn-sm">Generate</button>
              </div>
            </div>
          ))}
        </div>

        <div className="card-surface p-3">
          <p className="fw-semibold mb-3">Recent Reports</p>
          <div className="table-responsive">
            <table className="table admin-table mb-0">
              <thead>
                <tr>
                  <th>Report Name</th>
                  <th>Type</th>
                  <th>Generated On</th>
                  <th>Generated By</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                {recentReports.map((r) => (
                  <tr key={r.id}>
                    <td className="fw-medium">{r.name}</td>
                    <td className="text-muted-brand">{r.type}</td>
                    <td className="text-muted-brand">{r.generatedOn}</td>
                    <td className="text-muted-brand">{r.generatedBy}</td>
                    <td>
                      <button className="btn btn-sm border-0 p-0 text-primary-brand fw-semibold">
                        <i className="bi bi-download me-1" /> Download
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          <div className="text-end mt-2">
            <button className="btn btn-sm border-0 text-primary-brand fw-semibold">View all reports</button>
          </div>
        </div>
      </div>
    </>
  );
}
